version: '3'
services:
  kafka-relay:
    hostname: kafka-relay
    container_name: kafka-relay
    image: relay-to-kr1-stg-for-orders:0.1
    # networks:
    #   netgroup:
    #     ipv4_address: 172.18.0.101
    deploy:
      resources:
        limits:
          memory: 1g
# networks:
#   netgroup:
#     name: netgroup
#     driver: bridge
#     attachable: true
#     ipam:
#       config:
#         - subnet: 172.18.0.0/16
#           gateway: 172.18.0.1