LOGGING_LEVEL: 'INFO'
LOGGING_FORMAT: '%(asctime)-15s | %(levelname)s | %(filename)s | %(lineno)d: %(message)s'

WEB_HOST: '127.0.0.1'
WEB_PORT: 8006

KAFKA_BROKER: ['localhost:9092','localhost:9093','localhost:9094']
PROCESSED_DATA_TOPIC: "order_results"
# AVERAGE_CHANGELOG_TOPIC: "data-aggregator-average-changelog"

DB_URI: "postgresql+asyncpg://postgres:coc@127.0.0.1:5432/currencies"

# PROMETHEUS_PORT: 7006